### ISSUE TITLE
chaincode instantiate pod getting error

### ISSUE THREAD

**Issue by Abhinavsai18** [IBM/Hyperledger-Fabric-for-Trusted-IoT#10]
At the end of 3rd step in documentation, I am getting an error in the status of chaincode instantiate pod like this.
![ss32](https://user-images.githubusercontent.com/75847674/122088811-c1785c80-ce23-11eb-8267-50a39390b3b2.png)

**Comment by pmorrall** [comment]
kubectl logs chaincodeinstantiate-8n7kp
←[34m2021-06-16 19:04:54.020 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 001←[0m Using default escc
←[34m2021-06-16 19:04:54.020 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002←[0m Using default vscc
Error: could not assemble transaction, err proposal response was not successful, error code 500, msg error starting container: error starting container: Post http://localhost:2375/build?t=nid1-org1peer2-cc-1.0-00eb6ab3283c9baa2e0d3514c774f5b4025b081dcf0eac4a88ef3e72c6761cf5: Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:latest: API error (404): manifest for hyperledger/fabric-ccenv:latest not found

I just got the same error - not sure where its trying to pull

**Comment by yigitpolat** [comment]
Please take a look at #6

**Comment by pmorrall** [comment]
> Please take a look at #6

Spotted that late last night..thanks..
Still not working yet... join channel issues at the moment so checking the yamls.  It did join once until i reverted to test with the 1.4 version

**Comment by yigitpolat** [comment]
It's been a while developed it and didn't maintain afterwards. Images should be updated with the new versions and change the code with the CC lifecycle.

**Comment by Abhinavsai18** [comment]
> Please take a look at #6

I've already tried it earlier. But it doesn't worked at all :(

**Comment by Abhinavsai18** [comment]
> It's been a while developed it and didn't maintain afterwards. Images should be updated with the new versions and change the code with the CC lifecycle.

what do mean exactly? Can you suggest me what should I do more clearly.

**Comment by yigitpolat** [comment]
With HLF 2.0 there are many new changes in the chaincode lifecycle. YAML files needed to be updated with the new container image versions, besides besides according to documentation, there might be new changes in the chaincode deployment.

**Comment by yigitpolat** [comment]
@ljbennett62 lets close this issue as well. This is solved with John's PR.

**Comment by johnwalicki** [comment]
Closing ticket - fixed by https://github.com/IBM/Hyperledger-Fabric-for-Trusted-IoT/pull/11
