### ISSUE TITLE
GetHistory function failure

### ISSUE THREAD

**Issue by altunbaratli** [IBM/Hyperledger-Fabric-for-Trusted-IoT#4]
GetHistory function fails after several successful tries. After the failure the CA gets deleted and all the users get deleted. So, continuous addTemp transactions starts to fail as well.

**Comment by wuyg1226** [comment]
> GetHistory function fails after several successful tries. After the failure the CA gets deleted and all the users get deleted. So, continuous addTemp transactions starts to fail as well.

Dear altunbaratli,

How can i delete CA and all the registered users and admin? thank you for your help.

Best Wishes,
Ying

**Comment by yigitpolat** [comment]
@wuyg1226 you suppose the delete CA deployment. 
`kubectl delete deployment caorg1 `
But this not recommended as you will lose admin and all the user certificates. Do you have any purpose to do that?

**Comment by wuyg1226** [comment]
@yigitpolat 
Thank you for your reply. Because there was some user register conflict happen in my previous try, i think i can delete these certificates and re-deploy them. It is OK now when i clean all the pods and tried again. Thank you.

**Comment by yigitpolat** [comment]
@wuyg1226 no worries at all.
@ljbennett62 we can close this one.

**Comment by johnwalicki** [comment]
Closing issue.
