### ISSUE TITLE
Chaincode Instantiate is failing

### ISSUE THREAD

**Issue by Parth2412** [IBM/Hyperledger-Fabric-for-Trusted-IoT#6]
Hello, 

I hope you are doing well. 

I am following the steps of README.md and when I am trying to execute this command:
```kubectl apply -f chaincode_instantaite.yaml```

it is throwing this type of error:
![image](https://user-images.githubusercontent.com/23364077/94434388-587a8700-01b7-11eb-81d9-1182be897bee.png)

I have checked my docker images as well and the image *fabric-ccenv with latest tag*  is there, so I don't know what is the issue I have tried several times but the issue remains same.

Thanks.

**Comment by yigitpolat** [comment]
@Parth2412 This is the first time that I saw this issue. This repo already outdated and not maintaining anymore. Probably a version conflict causes this problem, because as far as I know chaincode life cycle had a new update and probably this proper way for the installation. I will spend sometime to make it available for version 2.0 or 2.2

**Comment by Parth2412** [comment]
> @Parth2412 This is the first time that I saw this issue. This repo already outdated and not maintaining anymore. Probably a version conflict causes this problem, because as far as I know chaincode life cycle had a new update and probably this proper way for the installation. I will spend sometime to make it available for version 2.0 or 2.2

@yigitpolat Thanks for the reply, 
Actually, I don't have an IBM account so I have set up the Kubernetes on localhost and trying to follow your tutorial so I guess this might not be the reason right? Correct me if I am wrong.
OR if this tutorial will work with the IBM cloud account so I will go with that.
The suggestion would be appreciated.

Thanks & Regards,

**Comment by yigitpolat** [comment]
I can't be sure about it. I don't think is causes the issue, however I suggest you to try IBM Cloud's Kubernetes Service free tier. 
Hopefully you will make it.
Thanks.

**Comment by thomasrueter** [comment]
Hi I need to confirm the issue. when the chaincode is gong to be initiated the fabric-ccenv container is pulled. Problem:ibmuser@IBPonOpenShift:~/Hyperledger-IoT/jobs$ docker pull hyperledger/fabric-ccenv
Using default tag: latest
Error response from daemon: manifest for hyperledger/fabric-ccenv:latest not found: manifest unknown: manifest unknown

So it can't be pulled ad the operation failed! 
But how to fix this? fabric-ccenv is not directly pulled by the  chaincode_instantaite.yaml

**Comment by thomasrueter** [comment]
2020-10-03 12:31:03.071 [INFO][89] table.go 497: Loading current iptables state and checking it is correct. ipVersion=0x4 table="filter" 
Oct 3 14:31:03 kube-bts5cj7f0s7ree35iqkg-myclusterfr-default-00000094 syslog Oct  3 12:31:03 kube-bts5cj7f0s7ree35iqkg-myclusterfr-default-00000094 ntpd[1316]: Listen normally on 46 calia88c72d0af7 [fe80::ecee:eeff:feee:eeee%39]:123 
Oct 3 14:31:03 kube-bts5cj7f0s7ree35iqkg-myclusterfr-default-00000094 syslog Oct  3 12:31:03 kube-bts5cj7f0s7ree35iqkg-myclusterfr-default-00000094 ntpd[1316]: Deleting interface #45 caliac9f1a4aa73, fe80::ecee:eeff:feee:eeee%38#123, interface stats: received=0, sent=0, dropped=0, active_time=5 secs 
Oct 3 14:31:03 kube-bts5cj7f0s7ree35iqkg-myclusterfr-default-00000094 syslog Oct  3 12:31:03 kube-bts5cj7f0s7ree35iqkg-myclusterfr-default-00000094 ntpd[1316]: new interface(s) found: waking up resolver 
Oct 3 14:31:03 calico-node-k5dgv calico-node 2020-10-03 12:31:03.089 [INFO][89] int_dataplane.go 1176: Finished applying updates to dataplane. msecToApply=21.279504000000003 
Oct 3 14:31:03 kube-bts5cj7f0s7ree35iqkg-myclusterfr-default-00000094 syslog Oct  3 12:31:03 kube-bts5cj7f0s7ree35iqkg-myclusterfr-default-00000094 kubelet.service[6557]: I1003 12:31:03.175870    6557 kubelet.go:1955] SyncLoop (PLEG): "chaincodeinstantiate-nm47r_default(422159e7-b6f1-4044-a2b3-3a5b57655f66)", event: &pleg.PodLifecycleEvent{ID:"422159e7-b6f1-4044-a2b3-3a5b57655f66", Type:"ContainerStarted", Data:"f126313b620444e82381295159d584c8847318103535dd639af3154d75e31c0b"} 
Oct 3 14:31:03 kube-bts5cj7f0s7ree35iqkg-myclusterfr-default-00000094 kubelet.log Oct  3 12:31:03 kube-bts5cj7f0s7ree35iqkg-myclusterfr-default-00000094 kubelet.service[6557]: I1003 12:31:03.175870    6557 kubelet.go:1955] SyncLoop (PLEG): "chaincodeinstantiate-nm47r_default(422159e7-b6f1-4044-a2b3-3a5b57655f66)", event: &pleg.PodLifecycleEvent{ID:"422159e7-b6f1-4044-a2b3-3a5b57655f66", Type:"ContainerStarted", Data:"f126313b620444e82381295159d584c8847318103535dd639af3154d75e31c0b"} 
Oct 3 14:31:04 org1peer2-57fd8d885c-tdzhc dind err time="2020-10-03T12:31:04.110995048Z" level=info msg="Attempting next endpoint for pull after error: manifest unknown: manifest unknown" 
Oct 3 14:31:04 org1peer2-57fd8d885c-tdzhc org1peer2 err 2020-10-03 15:31:04.111 +03 [chaincode.platform] func1 -> ERRO 05d Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:latest: API error (404): manifest for hyperledger/fabric-ccenv:latest not found 
Oct 3 14:31:04 org1peer2-57fd8d885c-tdzhc org1peer2 err 2020-10-03 15:31:04.112 +03 [dockercontroller] deployImage -> ERRO 05e Error building image: Post http://localhost:2375/build?t=nid1-org1peer2-cc-1.0-00eb6ab3283c9baa2e0d3514c774f5b4025b081dcf0eac4a88ef3e72c6761cf5: Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:latest: API error (404): manifest for hyperledger/fabric-ccenv:latest not found 
Oct 3 14:31:04 org1peer2-57fd8d885c-tdzhc org1peer2 err 2020-10-03 15:31:04.112 +03 [dockercontroller] deployImage -> ERRO 05f Build Output: 
Oct 3 14:31:04 org1peer2-57fd8d885c-tdzhc org1peer2 err ******************** 
Oct 3 14:31:04 org1peer2-57fd8d885c-tdzhc org1peer2 err ******************** 
Oct 3 14:31:04 org1peer2-57fd8d885c-tdzhc org1peer2 err 2020-10-03 15:31:04.117 +03 [endorser] callChaincode -> INFO 060 [channel1][0477652a] Exit chaincode: name:"lscc"  (1368ms) 
Oct 3 14:31:04 org1peer2-57fd8d885c-tdzhc org1peer2 err 2020-10-03 15:31:04.118 +03 [endorser] SimulateProposal -> ERRO 061 [channel1][0477652a] failed to invoke chaincode name:"lscc" , error: Post http://localhost:2375/build?t=nid1-org1peer2-cc-1.0-00eb6ab3283c9baa2e0d3514c774f5b4025b081dcf0eac4a88ef3e72c6761cf5: Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:latest: API error (404): manifest for hyperledger/fabric-ccenv:latest not found 
Oct 3 14:31:04 org1peer2-57fd8d885c-tdzhc org1peer2 err error starting container 
Oct 3 14:31:04 org1peer2-57fd8d885c-tdzhc org1peer2 err error starting container 
Oct 3 14:31:04 org1peer2-57fd8d885c-tdzhc org1peer2 err 2020-10-03 15:31:04.118 +03 [comm.grpc.server] 1 -> INFO 062 unary call completed {"grpc.start_time": "2020-10-03T15:31:02.749+03:00", "grpc.service": "protos.Endorser", "grpc.method": "ProcessProposal", "grpc.peer_address": "172.30.194.161:49288", "grpc.code": "OK", "grpc.call_duration": "1.369559709s"} 
Oct 3 14:31:04 chaincodeinstantiate-nm47r chaincodeinstantiate err Error: could not assemble transaction, err proposal response was not successful, error code 500, msg error starting container: error starting container: Post http://localhost:2375/build?t=nid1-org1peer2-cc-1.0-00eb6ab3283c9baa2e0d3514c774f5b4025b081dcf0eac4a88ef3e72c6761cf5: Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:latest: API error (404): manifest for hyperledger/fabric-ccenv:latest not found 
Oct 3 14:31:04 orderer-5f8fb8495b-pz925 orderer err 2020-10-03 15:31:04.124 +03 [orderer.common.broadcast] Handle -> WARN 011 Error reading from 172.30.194.161:45438: rpc error: code = Canceled desc = context canceled 
Oct 3 14:31:04 orderer-5f8fb8495b-pz925 orderer err 2020-10-03 15:31:04.124 +03 [comm.grpc.server] 1 -> INFO 012 streaming call completed {"grpc.start_time": "2020-10-03T15:31:02.749+03:00", "grpc.service": "orderer.AtomicBroadcast", "grpc.method": "Broadcast", "grpc.peer_address": "172.30.194.161:45438", "error": "rpc error: code = Canceled desc = context canceled", "grpc.code": "Canceled", "grpc.call_duration": "1.37562671s"}

**Comment by thomasrueter** [comment]
https://stackoverflow.com/questions/62860545/instantiation-of-chaincode-using-fabric-node-sdk-gives-api-error-404-manifest

**Comment by thomasrueter** [comment]
Unfortunately I have not been able to get the envirment variable int the instantiate.yaml file

CORE_CHAINCODE_BUILDER: hyperledger/fabric-ccenv:2.1 

It still tries to get the latest, which won't happen any longer.....

**Comment by lucarizzo** [comment]
@yigitpolat chaincode error. Can you solve it please? I have the same error of @Parth2412

**Comment by yigitpolat** [comment]
This repo is outdated and needs couple of changed to make it adapted to Hyperledger Fabric v2.x.

**Comment by lucarizzo** [comment]
So, what can I do? Have I to wait the creator of the project?
--
Luca Rizzo  sabato, 06 febbraio 2021, 11:08AM +01:00 da Yigit Polat  notifications@github.com :

**Comment by lucarizzo** [comment]
when I digit: kubectl apply -f chaincode_install.yaml  
it appears: job.batch/chaincodeinstall created

then I digit: kubectl get pods and I obtain: chaincode error
![IMG_20210204_131930](https://user-images.githubusercontent.com/72277605/107117697-6a161e80-687c-11eb-84a9-ab5a5bef11d9.jpg)

**Comment by lucarizzo** [comment]
@yigitpolat Can you help us please ?

**Comment by lucarizzo** [comment]
Has someone solved the problem ?

**Comment by dgome** [comment]
> Has someone solved the problem ?

Yes, was simple; I found the solution, it is because in the peers "yaml" in the network-deployment folder, you have to also put this in each yaml peer file:

```
- name: CORE_CHAINCODE_BUILDER
  value: hyperledger/fabric-ccenv:X.X
```
Replace X,X with the value of the docker image tag from:
https://hub.docker.com/r/hyperledger/fabric-ccenv/tags?page=1&ordering=last_updated

![image](https://user-images.githubusercontent.com/13984278/107862937-a0413880-6e50-11eb-9267-2d5b4823f6ee.png)

**Comment by janioxavier** [comment]
> > Has someone solved the problem ?
> 
> Yes, was simple; I found the solution, it is because in the peers "yaml" in the network-deployment folder, you have to also put this in each yaml peer file:
> 
> ```
> - name: CORE_CHAINCODE_BUILDER
>   value: hyperledger/fabric-ccenv:X.X
> ```
> 
> Replace X,X with the value of the docker image tag from:
> https://hub.docker.com/r/hyperledger/fabric-ccenv/tags?page=1&ordering=last_updated
> 
> ![image](https://user-images.githubusercontent.com/13984278/107862937-a0413880-6e50-11eb-9267-2d5b4823f6ee.png)

Doesn't work here :/

**Comment by dgome** [comment]
> 
> Doesn't work here :/

For this project you have to change the X.X for 1.4  - hyperledger/fabric-ccenv:1.4

**Comment by lucarizzo** [comment]
Thank you @janioxavier and @dgome ! 
Can I do this project without the kubernetes service ?

**Comment by yigitpolat** [comment]
@lucarizzo as all the pieces containerized you need to use kubernetes, docker, etc. However, if you decide to use docker, you suppose to change the yaml files according to that.

@dgome would you consider create a PR?

**Comment by johnwalicki** [comment]
Closing issue - Fixed by https://github.com/IBM/Hyperledger-Fabric-for-Trusted-IoT/pull/11
