### ISSUE TITLE
node-red

### ISSUE THREAD

**Issue by lucarizzo** [IBM/Hyperledger-Fabric-for-Trusted-IoT#7]
Hi, how can I connect my sensor (ESP32) to node-red ? 
Now I'm sending data into ibm watson. I have my device ID.
I tryied to put it in "IBM app in" in node-red but it doesn't work.
Can you help me, please ? 
Thank you
Luca

**Comment by yigitpolat** [comment]
Can you please provide additional information screenshots, logs, etc.?

**Comment by lucarizzo** [comment]
It all works until this point: if I write 
kubectl apply -f chaincode_install.yaml
It appears
job.batch/chaincodeinstall created
I check with get kubectl pods
and I read
Chaincode error
--
Luca Rizzo  sabato, 06 febbraio 2021, 11:13AM +01:00 da Yigit Polat  notifications@github.com :

**Comment by lucarizzo** [comment]
--
Luca Rizzo  sabato, 06 febbraio 2021, 11:13AM +01:00 da Yigit Polat  notifications@github.com :

**Comment by lucarizzo** [comment]
I am talking about chaincode error now
![Uploading IMG_20210204_131930.jpg…]()

**Comment by pmorrall** [comment]
![image](https://user-images.githubusercontent.com/39520966/122444724-c14d9d80-cf98-11eb-86e6-4c0dc0204d7d.png)

all deployed and up and running as expected - but no data in sensor history.  So i guess its not connected back correctly to the blockchain.  where can i start to debug?
I'm generating dummy data and its playload status is 200

**Comment by yigitpolat** [comment]
@pmorrall can you share node red's screen?

**Comment by wuyg1226** [comment]
Hi yigi, 
The same problem met with me, i can not get history data. Is there any other method to check if the data has been written into blockchain ledger.  

<img width="928" alt="1" src="https://user-images.githubusercontent.com/57666952/128609392-a5490ec9-99b2-4955-a512-e2d4525bc676.png">

Please see my node-red screenshot, i can not get data from the result debug model of the get history data flow. Could you help us with that? thank you so much
<img width="929" alt="2" src="https://user-images.githubusercontent.com/57666952/128609565-dceeb526-a093-4f4b-9096-1c0634fae17e.png">

**Comment by yigitpolat** [comment]
@wuyg1226 currently working on this and will notify you when I fix it in this threat.

**Comment by wuyg1226** [comment]
@yigitpolat 

Dear Yigit, it is OK now when i started a new try from the beginning of your tutorial, thank you

**Comment by yigitpolat** [comment]
@ljbennett62 we can close this issue.

**Comment by johnwalicki** [comment]
Closing ticket
