### ISSUE TITLE
Registration of node-red

### ISSUE THREAD

**Issue by Abhinavsai18** [IBM/Hyperledger-Fabric-for-Trusted-IoT#9]
I have completed the first 4 steps of documentation successfully. In the 5th step, while trying to register the node-red it is showing an error like this. Please help me to resolve it ASAP. Thankyou
![ss31](https://user-images.githubusercontent.com/75847674/121797975-39d2f800-cc41-11eb-879f-3a000dcb3cb0.png)

**Comment by yigitpolat** [comment]
You might be missing a step during the deployment of the network.
It seems like required certificates couldn't be found in the directory. You might have problem with storage as well.

**Comment by Abhinavsai18** [comment]
> You might be missing a step during the deployment of the network.
> It seems like required certificates couldn't be found in the directory. You might have problem with storage as well.

Could you please help to resolve the issue by suggesting the necessary steps I have to perform.

**Comment by yigitpolat** [comment]
I would suggest destroy the cluster and start from the beginning. Be careful to check if you face any warning or error.
